controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
test:
    path: /api/test
    controller: App\Controller\ApiController::test
